#!/bin/bash

# Slackware build script for lua51

# Copyright 2023 Andrew Clemons, Tokyo Japan
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=lua51
SRCNAM=${PRGNAM%51}
VERSION=${VERSION:-5.1.5}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
elif [ "$ARCH" = "aarch64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCNAM-$VERSION
tar xvf $CWD/$SRCNAM-$VERSION.tar.gz
cd $SRCNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# CVE-2014-5461 patch
patch -p1 < $CWD/0004-Fix-stack-overflow-in-vararg-functions.patch

# build .so - thanks arch maintainers
patch -p1 < $CWD/lua-arch.patch

sed -i 's,/usr/local,/usr,' src/luaconf.h
sed -i 's,/usr/local,/usr,' etc/lua.pc
sed -i "s,lib/lua,lib$LIBDIRSUFFIX/lua," src/luaconf.h Makefile
sed -i "s,prefix}/lib,prefix}/lib${LIBDIRSUFFIX},g" etc/lua.pc

# allow lua5.1 to co-exist with other lua versions
sed -i 's/llua/llua5.1/' etc/lua.pc
sed -i 's/\/include/\/include\/lua5.1/' etc/lua.pc

sed -i '/^LUA_A=/s/lua/lua5.1/' src/Makefile
sed -i '/^LUA_T=/s/lua/lua5.1/' src/Makefile
sed -i '/^LUA_SO=/s/lua/lua5.1/' src/Makefile
sed -i '/^LUAC_T=/s/luac/luac5.1/' src/Makefile

# use our cflags
sed -i 's/^CFLAGS=[[:space:]]*\([^\$]*\) \$.*$/CFLAGS ?= \1/' src/Makefile
sed -i '/^CFLAGS/a CFLAGS += $(MYCFLAGS)' src/Makefile

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
make linux

make \
  INSTALL_TOP=$PKG/usr \
  INSTALL_INC=$PKG/usr/include/lua5.1 \
  INSTALL_LIB=$PKG/usr/lib$LIBDIRSUFFIX \
  TO_BIN="lua5.1 luac5.1" \
  TO_LIB="liblua5.1.so liblua5.1.so.5.1 liblua5.1.so.$VERSION" \
  install

install -m644 -D etc/lua.pc $PKG/usr/lib$LIBDIRSUFFIX/pkgconfig/lua51.pc

(
  cd $PKG/usr/lib$LIBDIRSUFFIX/
  ln -s liblua5.1.so liblua.so.5.1
  ln -s liblua5.1.so liblua.so.$VERSION

  cd pkgconfig
  ln -s lua51.pc lua5.1.pc
  ln -s lua51.pc lua-5.1.pc
)

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

(
  cd $PKG/usr/man/man1
  mv lua.1 lua5.1.1
  mv luac.1 luac5.1.1
)

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  COPYRIGHT HISTORY README doc \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
